name: Build JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          javac main.java
          jar cfe Evidencia-final.jar main main.class

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-jar
          path: Evidencia-final.jar

